import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const allExperiments = [
  'barebones', 'ground', 'terrain', 'terrain2', 'lighting', 'shadowmap', 'particles', 'webgpu',
  'car', 'modelcar', 'interior', 'ragdoll',
  'controllers/wawa', 'controllers/shouldercam', 'controllers/click', 'controllers/isocam', 'controllers/animations',
  'events', 'store',
  'playerswitchtonpcandopendoor', 'npclifesimulator',
  'npc', 'scape',
  'retargeting', 'retargeting-basic',
  'xr', 'miladychess', 'miladysurfer',
  'playground', 'wfc/index.html',
]


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <div className="absolute top-2 left-2 bg-slate-500 rounded flex flex-col p-2">
          {allExperiments.map((item) => {
            return <div className={`tracking-[-.01em] ${geistMono.variable}`} key={item}>
              <Link href={`/${item}`}>{item}</Link>
            </div>
          })}
        </div>
      </body>
    </html>
  );
}
